version: '3'
services:
  clash:
    image: uxber/clash:latest
    container_name: clash
    network_mode: host # bridge
    restart: always
    # ports:
    #   - '7890:7890' # HTTP Proxy Port | Mixed Port
    #   - '9090:9090' # External Controller (Restful API)
    volumes:
      - './config.yaml:/clash/config.yaml'
